### ISSUE TITLE
We need fake containerd services.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri-containerd#20]
To better unit test functions of cri-containerd, we need a group of fake containerd services (similar with [fake docker client](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/fake_docker_client.go))

Containerd now has 4 kinds of services:
* content
* execution
* images
* rootfs

We can add a fake execution service first, because the execution api is more stable. And add others later when image management code is added and needs test.

/cc @kubernetes-incubator/maintainers-cri-containerd 
@heartlock Are you interested in this? This is a good start to get familiar with containerd and the code base.

**Comment by heartlock** [comment]
yes, I will take this task

**Comment by Random-Liu** [comment]
@heartlock Thanks!

**Comment by Random-Liu** [comment]
I assigned this to @xlgao-zju, because he's in the org now.

/cc @heartlock @Helen-Xie Please take a look.

**Comment by Helen-Xie** [comment]
ok, I will do it.

**Comment by Random-Liu** [comment]
I found that image store service and rootfs service are easier to fake, but content store is a little bit harder. And I'm not sure whether it's useful for us to fake at the content store level, given its interface is just every low level read write.

Let's only work on the image store and rootfs service now. For the content store, we could fake at higher level in the future.

**Comment by Random-Liu** [comment]
Just FYI, containerd is adding a new client library https://github.com/containerd/containerd/pull/904.

We should integrate and test at that level after it lands. It will be much easier.

**Comment by Random-Liu** [comment]
We'll add new fake of the containerd client after the client switch, punt to v0.2.0.

**Comment by Random-Liu** [comment]
This is unit test specific change. May not have time to get to it this release.

**Comment by Random-Liu** [comment]
As is mentioned in https://github.com/containerd/cri-containerd/issues/103. I think we have enough test coverage today.

We can add more integration test instead of adding fake service.
