### ISSUE TITLE
Make kubeadm `preflight-check` and `reset` less docker specific.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri-containerd#236]
This should be a kubeadm issue.

Track it here for now, and file corresponding kubeadm issue after we think this through.

**Comment by abhinandanpb** [comment]
kubeadm reset doesnt remove kube pods in kube-system namespace
```
docker@abhi-demo-moby-linux-0:~$ sudo kubeadm reset
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] docker doesn't seem to be running, skipping the removal of running kubernetes containers
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/lib/etcd]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
```

**Comment by ijc** [comment]
The one I've tripped over is the need to pass `--cri-socket` to `init` since the default is `/var/run/dockershim.sock`. Not sure if it can sensibly be autodetected.

Looks like `kubeadm` tries to detect the use of CRI in general by checking if `crictl` is in `$PATH`, but that doesn't help with finding the socket.

**Comment by Random-Liu** [comment]
I think this has been fixed. https://github.com/kubernetes/kubernetes/blob/1e8f40f42ba789e7a453764ea8115ed8859af91e/cmd/kubeadm/app/cmd/reset.go

kubeadm is using `crictl` today.
