### ISSUE TITLE
Distro packages for cri-containerd

### ISSUE THREAD

**Issue by mataneja** [containerd/cri-containerd#416]
As we approach cri-containerd beta release, its time to review packaging. We would like to work with various Linux distribution maintainers to produce and maintain cri-containerd package. 

The goal is for end users to be able to consume cri-containerd without having to learn and add custom repositories/sources. It will be useful to have packages for the following Linux distributions at a minimum:

- [ ] Debian
- [ ] Ubuntu
- [ ] Fedora
- [ ] Arch
- [ ] Alpine
- [ ] Gentoo 

Any help from the Linux distro maintainer community is greatly appreciated!

**Comment by Random-Liu** [comment]
I think based on current plan, we are going to ship cri-containerd with containerd.

Given so, can we close this issue?

**Comment by mikebrow** [comment]
Closing as a duplicate to https://github.com/containerd/containerd/issues/1508

**Comment by mataneja** [comment]
Yes, this should be fine!
