### ISSUE TITLE
How to handle packages using glog.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri-containerd#549]
We switched cri-containerd to use `logrus` instead of `glog` in https://github.com/containerd/cri-containerd/pull/547.

However, some of our kubernetes package dependencies are still using glog, e.g. streaming server.
It's hard to update kubernetes packages to use logrus, so we have to tolerant it anyway.

There are 2 options:
1) Do not handle it, just let glog logs to default files. The problem is that we'll not be able to see those log output in stderr/stdout, which may make debug hard in the future.
2) Keep go flags in containerd/cri-containerd. So that with containerd+cri integration, there will be both `--log-level` flag and glog flags.

@containerd/containerd-maintainers

**Comment by crosbymichael** [comment]
I think since we use `cli` and not go flags we could set the go flag in code, `flag.Set(name, value)` so it sends to stderr and the go flags will not show up in the `cli` output

**Comment by dnephin** [comment]
`glog` seems to violate a lot of the rules for good library design (setting flags from init outside of `main`, and not supporting any way to configure settings other than those flags).

Settings those from `flag.Set()` seems like a good short term solution. 

For a more long term solution, do you think the packages that currently use glog would accept a PR which removes the dependency and replaces it with a logging interface? The logging interface could then be implemented by any logging library using an adaptor (existing consumers could continue to use glog, but cri-containerd could use logrus).

Alternatively we could vendor a fork of glog that removes the flags, and adds support for configuring it properly from a `Config()` function. I think this option would be a lot easier.

**Comment by Random-Liu** [comment]
@crosbymichael @dnephin Thanks for the suggestion. I use `flag.Set()` in https://github.com/containerd/cri-containerd/pull/547 to set glog options based on `log-level` flag.

> For a more long term solution, do you think the packages that currently use glog would accept a PR which removes the dependency and replaces it with a logging interface? The logging interface could then be implemented by any logging library using an adaptor (existing consumers could continue to use glog, but cri-containerd could use logrus).

There are several Kubernetes packages we are relying on, I don't think it's easy to update them all. At least it's hard to justify in upstream. :(

I think using `flag.Set` is good enough for now. :) Thanks for the good suggestion!

**Comment by Random-Liu** [comment]
Close this one, since `flag.Set` can solve this problem.
