### ISSUE TITLE
Use containerd plugin log context.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri-containerd#550]
We switched cri-containerd to use logrus instead of glog in #547.

However, we are not using the plugin log context containerd passed to us.

We should use `containerd/log` package and make use that log context, so that there will be proper metadata in our log entry:
```
INFO[0000] LOG OUTPUT  module="containerd/io.containerd.grpc.v1.cri"
```

**Comment by Random-Liu** [comment]
@stevvooe @crosbymichael For grpc context, it seems that we need to integrate with the [`interceptor`](https://github.com/containerd/containerd/blob/master/server/server.go#L238).

Do we want to change the code directly after containerd vendors cri-containerd?
Or do we want that also to be pluggable?

**Comment by stevvooe** [comment]
#2019 should help here by removing the problem. ;)

**Comment by Random-Liu** [comment]
Since https://github.com/containerd/containerd/pull/2019 is merged, we don't need to care about this anymore.

Close.
