### ISSUE TITLE
use of insecure registry

### ISSUE THREAD

**Issue by kumudkhk** [containerd/cri-containerd#559]
In Docker, we were able to pull images from our private repo by including --insecure-registry option. I am not able to find any information in option to use insecure registry. Is it possible with containerd?

**Comment by abhi** [comment]
@kumudkhk we are working on a registry option and should be in shortly. Please try it out and let us know what you think.

**Comment by kumudkhk** [comment]
Thanks @abhi. Good to know that registry option is being worked on. Anytime frame on when it might be released?

**Comment by Random-Liu** [comment]
I think we've supported this with `-registry-mirror` flag.

We should document this.

**Comment by Random-Liu** [comment]
@kumudkhk Can you check out https://github.com/containerd/cri-containerd/blob/master/docs/registry.md?

Close this one.

**Comment by kumudkhk** [comment]
Thank you. I got back into k8s after few months. Looks great now. I was able to pull from a insecure-registry.

**Comment by qianzhangxa** [comment]
@Random-Liu @kumudkhk I tried to follow https://github.com/containerd/cri/blob/master/docs/registry.md#configure-registry-endpoint to make containerd can pull image from an insecure registry, but it failed.

I installed Harbor (`172.17.1.201`) as my registry, and I added it into `/etc/containerd/config.toml` as an insecure registry:
```
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."172.17.1.201"]
          endpoint = ["http://172.17.1.201:80"]
```
And then I ran `systemctl restart containerd` to restart containerd, but when I tried to pull an image, it still failed:
```
crictl pull 172.17.1.201/library/alpine 
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to resolve image "172.17.1.201/library/alpine:latest": no available registry endpoint: failed to do request: Head https://172.17.1.201/v2/library/alpine/manifests/latest: x509: certificate signed by unknown authority
```
So it seems containerd still connected to Harbor in HTTPS. Any ideas?

**Comment by yusiwen** [comment]
Still the same problem, even if my `/etc/containerd/config.toml` is configured as what suggested in the [ https://github.com/containerd/cri-containerd/blob/master/docs/registry.md]( https://github.com/containerd/cri-containerd/blob/master/docs/registry.md)

Any news?

**Comment by ABVitaliAUSY** [comment]
@yusiwen can I ask you to post the config or at least the part related to the registry? I managed to have it working with this conf:

```
[plugins."io.containerd.grpc.v1.cri".registry.configs."<registry-address>"]
   [plugins."io.containerd.grpc.v1.cri".registry.configs."<registry-address>".tls]
      insecure_skip_verify = true
```

Hope that it can help you.
