### ISSUE TITLE
Several issues we need to fix in ocicni.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri-containerd#573]
1) `ocicni` assumes that cni network configuration directory must exist before start, because it uses fsnotify monitoring that directory. This means that containerd+cri start may fail if there is no such directory, which is unacceptable, and causes some troubles during bootstrapping.
2) The fsnotify of `ocicni` doesn't actually work. See https://github.com/containerd/cri-containerd/issues/545.

We should fix it for the containerd+cri merge.

**Comment by Random-Liu** [comment]
@ijc Thanks for offering help! Assigned to you.

**Comment by ijc** [comment]
1. is an easy fix with a strategically placed `os.MkdirAll`, I'll make a PR for that.
2. Is a bit more complex, will discuss on #545.

**Comment by Random-Liu** [comment]
> is an easy fix with a strategically placed os.MkdirAll, I'll make a PR for that.

@ijc Yeah, I'm fine with `MkdirAll` in either cri-containerd or ocicni.

**Comment by Random-Liu** [comment]
@ijc I sent https://github.com/containerd/cri-containerd/pull/589, because we need that fix for the plugin mode. :)
