### ISSUE TITLE
OAuth and Private Docker Registry

### ISSUE THREAD

**Issue by hgfischer** [containerd/cri-containerd#610]
Hello,

I did setup a Kubernetes v1.9.3 cluster with v1.0.0-beta.1 release of cri-containerd and it seemed to work perfectly until I tried to use a private docker registry using JFrog Artifactory SaaS (https://www.jfrog.com/confluence/display/RTF/Docker+Registry).

It seems that cri-containerd is not sending HTTP Basic authentication while getting the OAuth token, and this is making it get HTTP 401 errors and not be able to get images from the registry.

Are you aware of this problem. Is it a known limitation? What do you suggest?

**Comment by hgfischer** [comment]
Also, I noticed there are many commits on the master branch that changes the authentication mechanisms and I was trying to test this build against my cluster, but it does not work. Kubelet complains of the new cri-containerd with the error bellow:

```
Feb 13 13:52:26 kubw01 kubelet[594]: E0213 13:52:26.104323     594 kuberuntime_manager.go:172] Get runtime version failed: rpc error: code = Unimplemented desc = unknown service runtime.RuntimeService
Feb 13 13:52:26 kubw01 kubelet[594]: error: failed to run Kubelet: failed to create kubelet: rpc error: code = Unimplemented desc = unknown service runtime.RuntimeService
```

Is it because the master branch is not compatible with the latest 1.9.3 release of Kubernetes (kubelet)? Can I easily fix this?

**Comment by hgfischer** [comment]
Just noticed that there is some incompatibility of `containerd` with `bearer` authentication on JFrog Docker Registry. I already reported the error to JFrog, with an example of a `curl` command to test the same request `cri-containerd` is doing. Forcing basic authentication works.

Are there any plans to fallback to other authentication methods when one doesn't work? For example, fall back to basic authentication when there is `username` and `secret` present and `bearer` doesn't work?

**Comment by Random-Liu** [comment]
@abhi Can you take a look at this?

> Also, I noticed there are many commits on the master branch that changes the authentication mechanisms and I was trying to test this build against my cluster, but it does not work.

HEAD will not be compatible with Kubernetes 1.9. CRI has been changed from `v1alpha1` to `v1alpha2`, which is a breaking change. We'll start guarantee backward compatibility when CRI is beta.
Before that each container runtime version will bind to a specific Kubernetes version.

**Comment by abhi** [comment]
@Random-Liu sure will take a look

**Comment by hgfischer** [comment]
I've debugged this issue a bit more and it seems to be some sort of incompatibility with the `/v2/token` endpoint of Artifactory's Docker Registry. I could not figure out what is wrong, but the endpoint always return HTTP 401 even thou the credentials are correct.

Then I patched the vendorized containerd inside cri-containerd to fallback to HTTP auth if getting a token fails and if there is username and password available and this fixed the problem.

Also, using Docker works fine with Artifactory, so I suppose it is either doing a fallback to HTTP auth OR there is some peculiar difference in the token request handling that might be more compatible with Artifactory. They probably implemented their Docker Registry testing only with Docker itself. I already reported this to them but still have no answer.

**Comment by abhi** [comment]
@hgfischer can you share the http capture of the failure ?

**Comment by hgfischer** [comment]
@abhi Yes, but redacted. The following is the reproduced request that I got while debugging `cri-containerd`:

```
curl -v -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'client_id=containerd-dist-tool&grant_type=password&password=********************&scope=repository%3Areponame%2Fimagename%3Apull&service=foo-docker-local.jfrog.io&username=username' https://foo-docker-local.jfrog.io/foobar/api/docker/docker-local/v2/token
```
Response (redacted):

```
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=Santa Clara; O=JFrog Inc.; OU=JFrog Inc.; CN=*.jfrog.io
*  start date: Mar  9 00:00:00 2016 GMT
*  expire date: Mar  9 23:59:59 2018 GMT
*  subjectAltName: host "foo-docker-local.jfrog.io" matched cert's "*.jfrog.io"
*  issuer: C=US; O=GeoTrust Inc.; CN=GeoTrust SSL CA - G3
*  SSL certificate verify ok.
> POST /foobar/api/docker/docker-local/v2/token HTTP/1.1
> Host: foo-docker-local.jfrog.io
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 195
> 
* upload completely sent off: 195 out of 195 bytes
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json;charset=ISO-8859-1
< Date: Wed, 14 Feb 2018 08:39:25 GMT
< Server: Artifactory/5.8.4-m002
< WWW-Authenticate: Basic realm="Artifactory Realm"
< X-Artifactory-Id: aolshared1a-foo
< X-Node: nginx-shared1a.prod-euc1
< Content-Length: 91
< Connection: keep-alive
< 
{
  "errors" : [ {
    "status" : 401,
    "message" : "Authentication is required"
  } ]
}
```

The following is the patch I did to work around the issue by falling back to HTTP Basic Auth when getting Oauth Token fails:

```
diff --git a/remotes/docker/resolver.go b/remotes/docker/resolver.go
index 57a18b66..7038ca1d 100644
--- a/remotes/docker/resolver.go
+++ b/remotes/docker/resolver.go
@@ -343,6 +343,12 @@ func (r *dockerBase) retryRequest(ctx context.Context, req *http.Request, respon
                                        return nil, err
                                }
                                if err := r.setTokenAuth(ctx, c.parameters); err != nil {
+                                       // NOTE Try a fallback to basic auth
+                                       if r.username != "" && r.secret != "" {
+                                               log.G(ctx).Debug("token auth failed, trying fallback to basic auth")
+                                               r.useBasic = true
+                                               return copyRequest(req)
+                                       }
                                        return nil, err
                                }
                                return copyRequest(req)
```

**Comment by dmcgowan** [comment]
This looks like a problem with the JFrog implementation, the POST body is not being properly handled. My guess is that it is being treated the same as a GET request. A properly implemented token server should handle the POST request or return 405.

This has a more general effect on pulling, closing this in favor of https://github.com/containerd/containerd/issues/2148
