### ISSUE TITLE
Can't build v1.0.0-beta.1 locally

### ISSUE THREAD

**Issue by t3hmrman** [containerd/cri-containerd#614]
While attempting to debug a crash (`crictl ps` will work, `crictl pull busybox` will cause cri-continerd to panic), I tried to install and build `v1.0.0-beta.1`, since that's the version I had the problem on.

While initially I built `cri-containerd` off of master, and it actually worked fine (+ `seccomp` and `selinux` tags), I realized I was on master and tried to go back and build v`1.0.0-beta.1` and it failed, citing missing code -- I think this is due to the change of repo name (after graduating from Kubernetes incubator?)

```
go build -o _output/cri-containerd \
        -tags 'seccomp apparmor' \
        -ldflags '-X github.com/kubernetes-incubator/cri-containerd/pkg/version.CRIContainerdVersion=1.0.0-beta.1' \
        -gcflags '' \
        github.com/kubernetes-incubator/cri-containerd/cmd/cri-containerd
can't load package: package github.com/kubernetes-incubator/cri-containerd/cmd/cri-containerd: cannot find package "github.com/kubernetes-incubator/cri-containerd/cmd/cri-containerd" in any of:
        /usr/lib/go/src/github.com/kubernetes-incubator/cri-containerd/cmd/cri-containerd (from $GOROOT)
        /home/<user>/go/src/github.com/kubernetes-incubator/cri-containerd/cmd/cri-containerd (from $GOPATH)
make: *** [Makefile:81: _output/cri-containerd] Error 1
```

There might not be much you all can actually do about this outside of instructing people to copy/symlink `$GOPATH/src/github.com/kubernetes-incubator/cri-containerd` to `$GOPATH/src/github.com/containerd/cri-containerd`

The actual issue I'm having is pretty perplexing too but figured I'd report this sooner rather than later.

**Workaround**
```
ln -s $GOPATH/src/github.com/containerd/cri-containerd $GOPATH/src/github.com/kubernetes-incubator/cri-containerd
```

**Comment by t3hmrman** [comment]
A follow up question (I don't think it's worth it's own ticket) -- Does `cri-containerd` *require* a custom build if `seccomp`and `apparmor` are enabled? The problem I was having just went away with a custom build, but the pre-packaged binary had the panic I was trying to debug earlier

For context, I'm running Kubernetes v1.9.2 by way of the kubernetes the hard way guide, on an Arch Linux box ([`libseccomp (aur)`](https://aur.archlinux.org/packages/libseccomp-git/) and [apparmor installed using the guide](https://wiki.archlinux.org/index.php/AppArmor)).

**Comment by mikebrow** [comment]
On master, we are in the middle of migrating from github.com/kubernetes-incubator/cri-containerd to github.com/containerd/cri-containerd and we retained git history.  Thus when you went back in time to before the start of the migration effort you necessitated that your source be github.com/kubernetes-incubator/cri-containerd based.  For me, I have an old git tree in my $GOPATH/src/github.com/kubernetes-incubator/cri-containerd and a new git tree in my $GOPATH/src/github.com/containerd/cri-containerd 

> A follow up question (I don't think it's worth it's own ticket) -- Does cri-containerd require a custom build if seccomp and apparmor are enabled? 

Use make install.deps to build and install all your dependencies. 

Cheers!

**Comment by t3hmrman** [comment]
Thanks for letting me know @mikebrow , I suspected it might be something like that. 
Sorry for the interruption!
