### ISSUE TITLE
Containerd drops support for golang 1.9.x

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri-containerd#626]
See https://github.com/containerd/containerd/pull/2162

They have pulled in a golang 1.10 library.. so now need 1.10 to build.

**Comment by Random-Liu** [comment]
Let's do the same. :)

**Comment by Random-Liu** [comment]
Let's close this issue after containerd build in Kubernetes test infra is also switched to golang 1.10.

**Comment by Random-Liu** [comment]
We can close this now. We've changed Kubernetes test-infra to build cri-containerd with golang 1.10.
