### ISSUE TITLE
couldn't parse cri-containerd version \"UNKNOWN\": No Major.Minor.Patch elements found

### ISSUE THREAD

**Issue by nim-nim** [containerd/cri-containerd#656]
```
Testing: "/builddir/build/BUILD/cri-containerd-1.0.0-beta.1/_build/src/github.com/containerd/cri-containerd/pkg/version"
+ GOPATH=/builddir/build/BUILD/cri-containerd-1.0.0-beta.1/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro  '\'''
--- FAIL: TestValidateSemver (0.00s)
        Error Trace:    version_test.go:32
        Error:          Expected nil, but got: &errors.errorString{s:"couldn't parse cri-containerd version \"UNKNOWN\": No Major.Minor.Patch elements found"}
        Test:           TestValidateSemver
FAIL
```

**Comment by Random-Liu** [comment]
@nim-nim We use git to generate a version string. `git describe --tags --dirty --always` (See [here](https://github.com/containerd/cri-containerd/blob/master/Makefile#L25))

You may want to use `make test` instead of `go test`, because the Makefile will inject the version for you.

And if you don't care about this for your development, you can ignore the test failure for now.

**Comment by nim-nim** [comment]
Hi,

1. `git describe --tags --dirty --always` does not work for release archive, since they cut the git link. 1.0.0-beta.1 is a release archive
2.  our golang maintainer is quite picky about the flags go test should use (for good reason, it's his job to make sure all compiler defaults are caught early) and makefiles tend to eat the flags we apply to all tests so plain go test with generic flags is what we use for all projects
3. it's one more test that needs manual blacklisting

Can you make it work for archive releases in `go test` please?

**Comment by Random-Liu** [comment]
@nim-nim We'll remove this unit test in https://github.com/containerd/cri-containerd/pull/653.

So basically you won't see this test in next release (coming by the end of March). :)

**Comment by nim-nim** [comment]
That's good to know, I hope the safety is somewhere else now (semver is good)

**Comment by Random-Liu** [comment]
@nim-nim It is containerd's responsibility now. :) `cri-containerd` will become a native plugin of containerd this release. It means that as long as you run containerd, it will natively support CRI.

And cri-containerd will just report the containerd version, because they are same thing now. :)
